### PR TITLE
#93我的应用-发布历史-版本历史页面优化 

### PR DESCRIPTION
**Pull request by qq763961731**
## 变更点(Changes)

- xxxx

## 相关issues (Which issues this PR fixes)

- Fixes #

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/bk-PaaS?pullRequest=125) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/bk-PaaS?pullRequest=125) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/bk-PaaS?pullRequest=125) it.</sub>

**Comment by wklken** [comment]
- 需要签 Contributor License Agreement, 见上面机器人comment

**Comment by wklken** [comment]
不要提交pr无关文件 `.idea/jsLinters/jshint.xml`

**Comment by wklken** [comment]
删除了README.md和`paas-ce/paas/paas/static/css/base.min.css`?

**Comment by qq763961731** [comment]
> 删除了README.md和`paas-ce/paas/paas/static/css/base.min.css`？

只删除README.md

**Pull request closed without merging**
